### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by crisdosaygo** [spencertipping/caterwaul#2]
Very cool project. When I couldn't find a license, a felt a little scared to use it because I'm not sure of the ramifications for my code or projects. Maybe this is something you could consider in future.

Recently I discovered some very cool licenses (but they are not "Open Source", AFAIK) -- [Polyform](https://polyformproject.org/)

**Comment by spencertipping** [comment]
Good call! Thanks for mentioning; I thought I had posted it somewhere.

Just added MIT via https://github.com/spencertipping/caterwaul/commit/4cb25f85c65e8ab6a82dd9a663a23b38e0e07101.
